spring.application.name=user-service

spring.datasource.url=jdbc:postgresql://localhost:5432/database-service
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.url=jdbc:postgresql://localhost:5432/database-service
spring.flyway.user=postgres
spring.flyway.password=postgres
spring.flyway.schemas=public
