spring.application.name=course

spring.datasource.url=jdbc:postgresql://localhost:5432/course-management
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.url=jdbc:postgresql://localhost:5432/course-management
spring.flyway.user=postgres
spring.flyway.password=123456
spring.flyway.schemas=public

